"""training load, compliance, gates, academic tracking

Revision ID: 07fec908e955
Revises: 451272f3bc5e
Create Date: 2026-09-23 16:03:23.693041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fec908e955'
down_revision: Union[str, None] = '451272f3bc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_training_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('load', sa.Float(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('estimated_sessions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'sport')
    )
    with op.batch_alter_table('daily_training_loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_training_loads_date'), ['date'], unique=False)

    op.create_table('injury_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('body_region', sa.String(), nullable=False),
    sa.Column('pain_scale', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injury_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injury_logs_date'), ['date'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_on', sa.Date(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('phase_gate_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('gate_date', sa.Date(), nullable=False),
    sa.Column('gate_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('criterion', sa.String(), nullable=False),
    sa.Column('evaluation', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('result_text', sa.String(), nullable=True),
    sa.Column('manual_status', sa.String(), nullable=True),
    sa.Column('recorded_on', sa.Date(), nullable=True),
    sa.Column('source_note', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('phase_gate_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase_gate_items_gate_date'), ['gate_date'], unique=False)

    op.create_table('planned_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_brick', sa.Boolean(), nullable=False),
    sa.Column('strength_type', sa.String(), nullable=True),
    sa.Column('study_tag', sa.String(), nullable=True),
    sa.Column('manual_status', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('planned_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_sessions_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_sessions_kind'), ['kind'], unique=False)

    op.create_table('recovery_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_baselines_metric'), ['metric'], unique=False)

    op.create_table('study_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_targets_effective_from'), ['effective_from'], unique=False)

    op.create_table('threshold_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('external_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_key')
    )
    with op.batch_alter_table('threshold_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threshold_tests_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_threshold_tests_test_date'), ['test_date'], unique=False)

    op.create_table('weighted_average_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('weighted_average_pct', sa.Float(), nullable=False),
    sa.Column('classification_estimate', sa.String(), nullable=True),
    sa.Column('modules_counted', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'recorded_on')
    )
    with op.batch_alter_table('weighted_average_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weighted_average_snapshots_academic_year'), ['academic_year'], unique=False)

    op.create_table('exam_prep_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_on', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['academic_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_prep_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_prep_items_module_id'), ['module_id'], unique=False)

    op.create_table('study_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['academic_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_logs_date'), ['date'], unique=False)

    op.create_table('academic_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['academic_assessments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['academic_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_deadlines_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_deadlines_module_id'), ['module_id'], unique=False)

    with op.batch_alter_table('academic_modules', schema=None) as batch_op:
        batch_op.alter_column('fheq_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relative_effort', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_watts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weighted_average_watts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('device_watts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('device_watts')
        batch_op.drop_column('weighted_average_watts')
        batch_op.drop_column('average_watts')
        batch_op.drop_column('relative_effort')

    with op.batch_alter_table('academic_modules', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fheq_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('academic_deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_deadlines_module_id'))
        batch_op.drop_index(batch_op.f('ix_academic_deadlines_due_at'))

    op.drop_table('academic_deadlines')
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_logs_date'))

    op.drop_table('study_logs')
    with op.batch_alter_table('exam_prep_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_prep_items_module_id'))

    op.drop_table('exam_prep_items')
    with op.batch_alter_table('weighted_average_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weighted_average_snapshots_academic_year'))

    op.drop_table('weighted_average_snapshots')
    with op.batch_alter_table('threshold_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threshold_tests_test_date'))
        batch_op.drop_index(batch_op.f('ix_threshold_tests_metric'))

    op.drop_table('threshold_tests')
    with op.batch_alter_table('study_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_targets_effective_from'))

    op.drop_table('study_targets')
    with op.batch_alter_table('recovery_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_baselines_metric'))

    op.drop_table('recovery_baselines')
    with op.batch_alter_table('planned_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_sessions_kind'))
        batch_op.drop_index(batch_op.f('ix_planned_sessions_event_id'))
        batch_op.drop_index(batch_op.f('ix_planned_sessions_date'))

    op.drop_table('planned_sessions')
    with op.batch_alter_table('phase_gate_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase_gate_items_gate_date'))

    op.drop_table('phase_gate_items')
    op.drop_table('milestones')
    with op.batch_alter_table('injury_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injury_logs_date'))

    op.drop_table('injury_logs')
    with op.batch_alter_table('daily_training_loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_training_loads_date'))

    op.drop_table('daily_training_loads')
    # ### end Alembic commands ###
