"""initial schema

Revision ID: 35f74319010b
Revises: 
Create Date: 2026-09-23 12:56:15.554536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f74319010b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calendar_tag', sa.String(), nullable=True),
    sa.Column('fheq_level', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_modules_academic_year'), 'academic_modules', ['academic_year'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sport_type', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    op.create_index(op.f('ix_activities_external_id'), 'activities', ['external_id'], unique=True)
    op.create_index(op.f('ix_activities_sport'), 'activities', ['sport'], unique=False)
    op.create_table('weekly_training_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_label', sa.String(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('target_minutes', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_training_targets_week_start_date'), 'weekly_training_targets', ['week_start_date'], unique=False)
    op.create_table('academic_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('mark_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['academic_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_assessments')
    op.drop_index(op.f('ix_weekly_training_targets_week_start_date'), table_name='weekly_training_targets')
    op.drop_table('weekly_training_targets')
    op.drop_index(op.f('ix_activities_sport'), table_name='activities')
    op.drop_index(op.f('ix_activities_external_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_academic_modules_academic_year'), table_name='academic_modules')
    op.drop_table('academic_modules')
    # ### end Alembic commands ###
