"""add garmin updated_at, distance on-track pct

Revision ID: 451272f3bc5e
Revises: 5584bf35276e
Create Date: 2026-09-23 15:12:39.569486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451272f3bc5e'
down_revision: Union[str, None] = '5584bf35276e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garmin_daily_metrics', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garmin_daily_metrics', 'updated_at')
    # ### end Alembic commands ###
