"""add competitors

Revision ID: 4fd9c1808179
Revises: 35f74319010b
Create Date: 2026-09-23 14:45:50.490901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd9c1808179'
down_revision: Union[str, None] = '35f74319010b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_activities_date'), 'competitor_activities', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_activities_date'), table_name='competitor_activities')
    op.drop_table('competitor_activities')
    op.drop_table('competitors')
    # ### end Alembic commands ###
