"""add nutrition and garmin tables

Revision ID: 5584bf35276e
Revises: e8d08749a161
Create Date: 2026-09-23 15:04:41.323126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5584bf35276e'
down_revision: Union[str, None] = 'e8d08749a161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garmin_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_min', sa.Float(), nullable=True),
    sa.Column('body_battery_high', sa.Integer(), nullable=True),
    sa.Column('body_battery_low', sa.Integer(), nullable=True),
    sa.Column('training_readiness', sa.Integer(), nullable=True),
    sa.Column('hrv_status', sa.String(), nullable=True),
    sa.Column('hrv_value', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('vo2max_running', sa.Float(), nullable=True),
    sa.Column('training_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garmin_daily_metrics_date'), 'garmin_daily_metrics', ['date'], unique=True)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('followed_plan', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_date'), 'nutrition_logs', ['date'], unique=False)
    op.create_table('supplement_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('timing', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplement_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_logs_date'), 'supplement_logs', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplement_logs_date'), table_name='supplement_logs')
    op.drop_table('supplement_logs')
    op.drop_table('supplement_protocols')
    op.drop_index(op.f('ix_nutrition_logs_date'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_garmin_daily_metrics_date'), table_name='garmin_daily_metrics')
    op.drop_table('garmin_daily_metrics')
    # ### end Alembic commands ###
