"""add distance targets

Revision ID: e8d08749a161
Revises: 4fd9c1808179
Create Date: 2026-09-23 15:03:15.433369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d08749a161'
down_revision: Union[str, None] = '4fd9c1808179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_training_targets', sa.Column('target_distance_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_training_targets', 'target_distance_km')
    # ### end Alembic commands ###
